//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadSuiteNet.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RadSuite.NET")]
        public string ApplicationTitle {
            get {
                return ((string)(this["ApplicationTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rad Project (*.rad)|*.rad|All Data Sources (*.accdb;*.mdb)|*.accdb;*.mdb")]
        public string OpenFileFilter {
            get {
                return ((string)(this["OpenFileFilter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rad Project (*.rad)|*.rad|Excel Workbook (*.xlsx)|*.xlsx|Excel 97-2003 Workbook (" +
            "*.xls)|*.xls|CSV (Comma delimited) (*.csv)|*.csv|Text (Tab delimited) (*.txt)|*." +
            "txt|Text (Pipe delimited) (*.txt)|*.txt|All Files (*.*)|*.*")]
        public string SaveAsFileFilter {
            get {
                return ((string)(this["SaveAsFileFilter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("All Files (*.*)|*.*|Text Files (*.txt;*.csv)|*.txt;*.csv|Excel Workbooks (*.xlsx;" +
            "*.xls)|*.xlsx;*.xls|Access Databases (*.accdb;*.mdb)|*.accdb;*.mdb")]
        public string ImportFileFilter {
            get {
                return ((string)(this["ImportFileFilter"]));
            }
        }
    }
}
